CREATE OR REPLACE USER dbt_user PASSWORD = 'q';
GRANT ROLE dbt_dev_role TO USER dbt_user;

ALTER USER dbt_user SET RSA_PUBLIC_KEY='-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsYgfd+opCsw9rexFtj2f
FvQ6MuXwjekCu2s+1WDxStCIfdrgrMOph4fBRpkY8Q9WKWXPpN0dmS28nuhfhzEJ
O9Rhk89u11yvGvdjkpm2ctiOGh2ZxSW3zgPild7VPJWv+cK8D51RtziTHM8I/6m/
3XSRkY9yM9zZ6pfpv9DVsmDXhsYVuDESa63nvNl8xzLqIpaZfyxu0GwH8a3sRNmE
kcNcE994qSPypAVRIswf7LWfFSzIHUbOx8/TpTGE3vs5S5IN+bTPEkXsCdYz+YsH
Y36t2v7kF462UjwzPWVHeZmNtE95utkGW8HRKV+FhNyUBtvveLtWSrc+H7WYt0hR
5wIDAQAB
-----END PUBLIC KEY-----';

DESC USER dbt_user;